[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "visionbot-sdk"
version = "0.1.0"
description = "A high-performance Android automation SDK featuring low-latency frame grabbers and instant touch injection."
readme = "README.md"
authors = [
    { name = "Dhruv Jain" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Testing",
    "Topic :: Games/Entertainment",
]
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "opencv-python",
    "pillow"
]

[project.optional-dependencies]
gui = [
    "PyQt6"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["visionbot*"]
